language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t hir0protagonist/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hir0protagonist/docker-react npm run test